version: "3.7"

services:
  database:
    image: postgres
    container_name: database
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=rentx
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    container_name: rentx
    build: .
    ports: 
      - "3333:3333"
    volumes:
      - .:/usr/app
    network_mode: host
volumes:
    pgdata:
      driver: local